name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Шаг 1: Получаем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      # Шаг 2: Настраиваем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Шаг 3: Создаем папку с версией и копируем туда файлы
      - name: Prepare versioned deployment
        run: |
          mkdir -p _site
          cp -R index.html ru en _site/
          echo "Содержимое _site:"
          ls -R _site

      # Шаг 4: Деплоим на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
